"""edit string to var

Revision ID: 3c08917f8aba
Revises: f1ad0c339aad
Create Date: 2022-05-16 10:15:31.213524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c08917f8aba'
down_revision = 'f1ad0c339aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
