"""Second fix

Revision ID: 6f14ba7e392f
Revises: 812bd280db59
Create Date: 2022-05-27 06:54:33.480603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f14ba7e392f'
down_revision = '812bd280db59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('internal_employee', 'isActive',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               nullable=True)
    op.create_foreign_key(None, 'internal_employee', 'employee_status', ['statusId'], ['id'])
    op.create_foreign_key(None, 'internal_employee', 'nationality_gender', ['nationalityGenderId'], ['id'])
    op.create_foreign_key(None, 'internal_employee', 'military_service_attitude', ['militaryServiceAttitudeId'], ['id'])
    op.create_foreign_key(None, 'internal_employee', 'ldap_login', ['ldapLoginId'], ['id'])
    op.create_foreign_key(None, 'internal_employee', 'grade', ['gradeId'], ['id'])
    op.create_foreign_key(None, 'internal_employee', 'marital_status', ['maritalStatusId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'internal_employee', type_='foreignkey')
    op.drop_constraint(None, 'internal_employee', type_='foreignkey')
    op.drop_constraint(None, 'internal_employee', type_='foreignkey')
    op.drop_constraint(None, 'internal_employee', type_='foreignkey')
    op.drop_constraint(None, 'internal_employee', type_='foreignkey')
    op.drop_constraint(None, 'internal_employee', type_='foreignkey')
    op.alter_column('internal_employee', 'isActive',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
